# Generated by Django 6.0.2 on 2026-03-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism familiya')),
                ('photo', models.ImageField(upload_to='worker_photo/')),
                ('stage', models.BigIntegerField(max_length=100, verbose_name='Lavozim')),
                ('phone1', models.CharField(max_length=15, verbose_name='Tel. raqam 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. raqam 2')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(verbose_name='Batafsil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('applicant', models.CharField(max_length=40, verbose_name='Arizachi')),
                ('phone1', models.CharField(max_length=15, verbose_name='Tel. raqam 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. raqam 2')),
                ('status', models.CharField(choices=[('qabul_qilingan', 'Qabul qilingan'), ('organib_chiqilmoqda', 'Organib chiqilmoqda'), ('rad_etilgan', 'Rad etilgan'), ('hal_qilingan', 'Hal qilingan')], default='qabul_qilingan', max_length=50)),
                ('created_on', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='mainapp.category')),
            ],
        ),
    ]
