# Generated by Django 6.0.2 on 2026-03-06 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone1',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Raqam xato ! Namuna: +998991112233', regex='^[+]998[0-9]{9}$')], verbose_name='Tel. raqam 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato ! Namuna: +998991112233', regex='^[+]998[0-9]{9}$')], verbose_name='Tel. raqam 2'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone1',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Raqam xato ! Namuna: +998991112233', regex='^[+]998[0-9]{9}$')], verbose_name='Tel. raqam 1'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Raqam xato ! Namuna: +998991112233', regex='^[+]998[0-9]{9}$')], verbose_name='Tel. raqam 2'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='stage',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
    ]
